# Generated by Django 5.0.3 on 2024-03-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=30)),
                ('species', models.CharField(max_length=60)),
                ('char_type', models.CharField(max_length=80)),
                ('gender', models.CharField(max_length=30)),
                ('image', models.TextField()),
            ],
        ),
    ]
